'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class compra
    Public Property IdComp As String
    Public Property idTransaccion As Long
    Public Property fecha As Nullable(Of Date)
    Public Property total As Nullable(Of Decimal)
    Public Property tipo As String
    Public Property usuario As String
    Public Property proveedor As String
    Public Property idProveedor As Long
    Public Property estado As String
    Public Property motivo As String
    Public Property numeroFactura As String

End Class
