'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class complementopagosh
    Public Property n_pago As Integer
    Public Property total As Nullable(Of Decimal)
    Public Property cliente As String
    Public Property id_cliente As Nullable(Of Integer)
    Public Property fecha_pago As Nullable(Of Date)
    Public Property formapago As String
    Public Property UsoCFDI As String
    Public Property UUID As String
    Public Property Cancelado As Nullable(Of Short)

End Class
