'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class pvEntitiesSalvador
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=pvEntitiesSalvador")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tblClientes() As DbSet(Of tblClientes)
    Public Overridable Property tblCobrars() As DbSet(Of tblCobrar)
    Public Overridable Property tblComplementoPagosDs() As DbSet(Of tblComplementoPagosD)
    Public Overridable Property tblComplementoPagosHes() As DbSet(Of tblComplementoPagosH)
    Public Overridable Property tblConfiguracions() As DbSet(Of tblConfiguracion)
    Public Overridable Property tblCotizacions() As DbSet(Of tblCotizacion)
    Public Overridable Property tblFacturaTotals() As DbSet(Of tblFacturaTotal)
    Public Overridable Property tblFacturas() As DbSet(Of tblFactura)
    Public Overridable Property tblFamilias() As DbSet(Of tblFamilia)
    Public Overridable Property tblFolioFacturas() As DbSet(Of tblFolioFacturas)
    Public Overridable Property tblFoliosTickets() As DbSet(Of tblFoliosTicket)
    Public Overridable Property tblGrupos() As DbSet(Of tblGrupos)
    Public Overridable Property tblHistorialPagos() As DbSet(Of tblHistorialPagos)
    Public Overridable Property tblLineas() As DbSet(Of tblLinea)
    Public Overridable Property tblMarcas() As DbSet(Of tblMarcas)
    Public Overridable Property tblNCs() As DbSet(Of tblNC)
    Public Overridable Property tblNcDetalles() As DbSet(Of tblNcDetalle)
    Public Overridable Property productos() As DbSet(Of tblProductos)
    Public Overridable Property tblProveedors() As DbSet(Of tblProveedor)
    Public Overridable Property tblSubFamilias() As DbSet(Of tblSubFamilia)
    Public Overridable Property tblbancoes() As DbSet(Of tblbanco)
    Public Overridable Property tbldiascreditoes() As DbSet(Of tbldiascredito)
    Public Overridable Property tblFormaDePagoes() As DbSet(Of tblFormaDePago)
    Public Overridable Property tblmetodopagoes() As DbSet(Of tblmetodopago)
    Public Overridable Property tblparametroes() As DbSet(Of tblparametro)
    Public Overridable Property tblregimenfiscals() As DbSet(Of tblregimenfiscal)
    Public Overridable Property tblTipoDeRelacions() As DbSet(Of tblTipoDeRelacion)
    Public Overridable Property tblUsoDeCFDIs() As DbSet(Of tblUsoDeCFDI)
    Public Overridable Property tblTickets() As DbSet(Of tblTicket)
    Public Overridable Property ticket_com() As DbSet(Of ticket_com)
    Public Overridable Property tblTicketCotizas() As DbSet(Of tblTicketCotiza)
    Public Overridable Property tblTicketPedidoes() As DbSet(Of tblTicketPedido)
    Public Overridable Property tblUnidades() As DbSet(Of tblUnidades)
    Public Overridable Property tblUsuarios() As DbSet(Of tblUsuarios)
    Public Overridable Property tblVentas() As DbSet(Of tblVenta)
    Public Overridable Property tblVentaPedidoes() As DbSet(Of tblVentaPedido)

End Class
