'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class pvEntitiesWendy
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=pvEntitiesWendy")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tblWClientes() As DbSet(Of tblWClientes)
    Public Overridable Property tblWConfiguracions() As DbSet(Of tblWConfiguracion)
    Public Overridable Property tblWFacturaTorals() As DbSet(Of tblWFacturaToral)
    Public Overridable Property tblWHistorialPagos() As DbSet(Of tblWHistorialPagos)
    Public Overridable Property tblWVventas() As DbSet(Of tblWVventas)
    Public Overridable Property tblWVentasPedidos() As DbSet(Of tblWVentasPedidos)
    Public Overridable Property tblWCobrars() As DbSet(Of tblWCobrar)

End Class
