'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class historial_pagos_proveedores
    Public Property id As Long
    Public Property fecha As Date
    Public Property numeroCompra As String
    Public Property total As Decimal
    Public Property claveProveedor As Long
    Public Property proveedor As String
    Public Property observaciones As String
    Public Property movimientoPagar As Long

End Class
