'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class pv_salvadorEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=pv_salvadorEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tblClientes() As DbSet(Of tblClientes)
    Public Overridable Property complementopagosds() As DbSet(Of complementopagosd)
    Public Overridable Property complementopagoshes() As DbSet(Of complementopagosh)
    Public Overridable Property compras() As DbSet(Of compra)
    Public Overridable Property tblConfiguracions() As DbSet(Of tblConfiguracion)
    Public Overridable Property tblFacturaTotals() As DbSet(Of tblFacturaTotal)
    Public Overridable Property tblFamilias() As DbSet(Of tblFamilia)
    Public Overridable Property tblFoliofacturas() As DbSet(Of tblFoliofacturas)
    Public Overridable Property tblFoliosTickets() As DbSet(Of tblFoliosTicket)
    Public Overridable Property tblGrupos() As DbSet(Of tblGrupos)
    Public Overridable Property historial_pagos_proveedores() As DbSet(Of historial_pagos_proveedores)
    Public Overridable Property tblLineas() As DbSet(Of tblLinea)
    Public Overridable Property tblNCs() As DbSet(Of tblNC)
    Public Overridable Property ordencompras() As DbSet(Of ordencompra)
    Public Overridable Property pagars() As DbSet(Of pagar)
    Public Overridable Property tblProveedors() As DbSet(Of tblProveedor)
    Public Overridable Property salidas() As DbSet(Of salida)
    Public Overridable Property tblSubFamilias() As DbSet(Of tblSubFamilia)
    Public Overridable Property tblbancoes() As DbSet(Of tblbanco)
    Public Overridable Property tblDiasCreditoes1() As DbSet(Of tblDiasCredito)
    Public Overridable Property tblFormaPagoes1() As DbSet(Of tblFormaPago)
    Public Overridable Property tblMetodoPagoes1() As DbSet(Of tblMetodoPago)
    Public Overridable Property tblParametroes1() As DbSet(Of tblParametro)
    Public Overridable Property tblUsoCFDIs1() As DbSet(Of tblUsoCFDI)
    Public Overridable Property tblUsuarios() As DbSet(Of tblUsuarios)
    Public Overridable Property tblVentas() As DbSet(Of tblVenta)
    Public Overridable Property ordencomprades() As DbSet(Of ordencomprade)
    Public Overridable Property tblTickets() As DbSet(Of tblTicket)
    Public Overridable Property nc_detalle() As DbSet(Of nc_detalle)
    Public Overridable Property tblVentaPedidoes() As DbSet(Of tblVentaPedido)
    Public Overridable Property tblTicketPedidoes() As DbSet(Of tblTicketPedido)
    Public Overridable Property tblTicketCotizas() As DbSet(Of tblTicketCotiza)
    Public Overridable Property tblCotizacions() As DbSet(Of tblCotizacion)
    Public Overridable Property productos() As DbSet(Of tblProductos)
    Public Overridable Property tblHistorialPagos() As DbSet(Of tblHistorialPagos)
    Public Overridable Property tblCobrars() As DbSet(Of tblCobrar)
    Public Overridable Property tblFacturas() As DbSet(Of tblFactura)
    Public Overridable Property tblMarcas() As DbSet(Of tblMarcas)
    Public Overridable Property tblUnidades() As DbSet(Of tblUnidades)
    Public Overridable Property tblTipoDeRelacions() As DbSet(Of tblTipoDeRelacion)

    Public Overridable Function SP_DB_BACKUP(databaseName As String, fullPath As String) As Integer
        Dim databaseNameParameter As ObjectParameter = If(databaseName IsNot Nothing, New ObjectParameter("DatabaseName", databaseName), New ObjectParameter("DatabaseName", GetType(String)))

        Dim fullPathParameter As ObjectParameter = If(fullPath IsNot Nothing, New ObjectParameter("FullPath", fullPath), New ObjectParameter("FullPath", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("SP_DB_BACKUP", databaseNameParameter, fullPathParameter)
    End Function

End Class
