'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class nc_detalle
    Public Property Id As Integer
    Public Property n_nc As Long
    Public Property idProducto As Long
    Public Property folio As String
    Public Property FolioFactura As String
    Public Property clave_p As String
    Public Property descripcion As String
    Public Property fecha As Date
    Public Property precio As Decimal
    Public Property cantidad As Decimal
    Public Property subtotal As Decimal
    Public Property IVA As Nullable(Of Decimal)
    Public Property ClaveProducto As String
    Public Property ClaveUnidad As String

End Class
