'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ordencompra
    Public Property nCompra As Long
    Public Property fechaoc As Date
    Public Property proveedor As String
    Public Property idProveedor As String
    Public Property atencion As String

End Class
