'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ordencompra
    Public Property IdComp As String
    Public Property nCompra As Long
    Public Property fechaoc As Date
    Public Property proveedor As String
    Public Property idProveedor As String
    Public Property atencion As String

End Class
