'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class pagar
    Public Property id As Long
    Public Property n_remision As Long
    Public Property total As Decimal
    Public Property fecha_compra As Date
    Public Property fecha_limite As Date
    Public Property proveedor As String
    Public Property resto As Decimal
    Public Property clave_proveedor As Integer

End Class
