'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class pagar
    Public Property IdComp As String
    Public Property id As Long
    Public Property n_remision As Long
    Public Property total As Decimal
    Public Property fecha_compra As Date
    Public Property fecha_limite As Date
    Public Property proveedor As String
    Public Property resto As Decimal
    Public Property clave_proveedor As Integer

End Class
