'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class proveedor
    Public Property IdComp As String
    Public Property clave As Long
    Public Property razonSocial As String
    Public Property calle As String
    Public Property numero As String
    Public Property colonia As String
    Public Property ciudad As String
    Public Property estado As String
    Public Property cp As String
    Public Property rfc As String
    Public Property telefono As String
    Public Property celular As String
    Public Property correo As String
    Public Property contacto As String
    Public Property observaciones As String

End Class
