'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class salida
    Public Property Id As Long
    Public Property total As Nullable(Of Decimal)
    Public Property motivo As String
    Public Property fecha As Nullable(Of Date)

End Class
