'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCotizacion
    Public Property nticket As Long
    Public Property fecha As Nullable(Of Date)
    Public Property SubTotal As Nullable(Of Decimal)
    Public Property IVA As Nullable(Of Decimal)
    Public Property total As Nullable(Of Decimal)
    Public Property tipo As String
    Public Property usuario As String
    Public Property cliente As String
    Public Property idCliente As Long
    Public Property estado As String
    Public Property motivo As String
    Public Property numeroFactura As String

End Class
