'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCobrar
    Public Property IdComp As String
    Public Property Id As Long
    Public Property n_remision As Long
    Public Property total As Nullable(Of Decimal)
    Public Property fecha_venta As Nullable(Of Date)
    Public Property fecha_limite As Nullable(Of Date)
    Public Property cliente As String
    Public Property resto As Decimal
    Public Property claveCliente As String
    Public Property tipoDocumento As String
    Public Property facturado As Nullable(Of Long)

End Class
