'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblConfiguracion
    Public Property Id As Long
    Public Property IdTerminal As String
    Public Property nombreEmpresa As String
    Public Property direccionEmpresa As String
    Public Property localidadEmpresa As String
    Public Property telefonoEmpresa As String
    Public Property ciudadEmpresa As String
    Public Property rfcEmpresa As String
    Public Property propietario As String
    Public Property impresiones As Nullable(Of Integer)
    Public Property factorIVA As Decimal
    Public Property cajaChica As Decimal
    Public Property logotipo As String
    Public Property folioFactura As Long
    Public Property InvoicePrinterName As String
    Public Property TicketPrinterName As String
    Public Property TipoCambio As Nullable(Of Decimal)
    Public Property RegimenFiscal As String
    Public Property LugarExpedicion As String

End Class
