'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblClientes
    Public Property clave As Long
    Public Property nombre As String
    Public Property apat As String
    Public Property amat As String
    Public Property calle As String
    Public Property numero As String
    Public Property colonia As String
    Public Property ciudad As String
    Public Property estado As String
    Public Property cp As String
    Public Property rfc As String
    Public Property telefono As String
    Public Property celular As String
    Public Property correo As String
    Public Property observaciones As String
    Public Property listaPrecios As String
    Public Property diasCredito As Integer
    Public Property limiteCredito As Decimal
    Public Property tipo_venta As String
    Public Property metodopago As String
    Public Property codiciones As String
    Public Property cuenta As String
    Public Property banco As String
    Public Property tasa_cero As Nullable(Of Integer)
    Public Property FormaPago As String
    Public Property UsoCFDI As String

End Class
