'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblComplementoPagosH
    Public Property IdComp As String
    Public Property n_pago As Integer
    Public Property total As Nullable(Of Decimal)
    Public Property cliente As String
    Public Property id_cliente As Nullable(Of Integer)
    Public Property fecha_pago As Nullable(Of Date)
    Public Property formapago As String
    Public Property UsoCFDI As String
    Public Property UUID As String
    Public Property Cancelado As Nullable(Of Short)

End Class
