'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCobrar
    Public Property Id As Long
    Public Property n_remision As Nullable(Of Long)
    Public Property total As Nullable(Of Decimal)
    Public Property fecha_venta As Nullable(Of Date)
    Public Property fecha_limite As Nullable(Of Date)
    Public Property cliente As String
    Public Property resto As Decimal
    Public Property claveCliente As String
    Public Property tipoDocumento As String

End Class
