'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblFacturaTotal
    Public Property n_factura As Decimal
    Public Property total As Decimal
    Public Property usuario As String
    Public Property tipo_venta As String
    Public Property cliente As String
    Public Property id_cliente As String
    Public Property fecha_venta As Date
    Public Property fecha_limite As Nullable(Of Date)
    Public Property codiciones As String
    Public Property estado As String
    Public Property observaciones As String
    Public Property facturaDia As Integer
    Public Property metodopago As String
    Public Property nc As String
    Public Property cuenta As String
    Public Property banco As String
    Public Property FormaPago As String
    Public Property UsoCFDI As String
    Public Property UUID As String
    Public Property Cancelada As Nullable(Of Short)
    Public Property ComproPago As Nullable(Of Short)
    Public Property pdf As String

End Class
