'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblFoliofacturas
    Public Property TipoComprobante As String
    Public Property Year As Integer
    Public Property FolioInicial As Nullable(Of Integer)
    Public Property FolioFinal As Nullable(Of Integer)
    Public Property FolioActual As Nullable(Of Integer)

End Class
