'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblFactura
    Public Property Id As Integer
    Public Property n_factura As Long
    Public Property folio As String
    Public Property idProducto As Nullable(Of Long)
    Public Property clave_p As String
    Public Property descripcion As String
    Public Property cantidad As Decimal
    Public Property fecha As Date
    Public Property subtotal As Decimal
    Public Property IVA As Nullable(Of Decimal)
    Public Property precio As Decimal
    Public Property ClaveProducto As String
    Public Property ClaveUnidad As String

End Class
