'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblGrupos
    Public Property clave As Long
    Public Property descripcion As String
    Public Property factorCosto As Decimal
    Public Property factorPublico As Decimal
    Public Property factorP1 As Decimal
    Public Property factorP2 As Decimal
    Public Property factorP3 As Decimal

End Class
