'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblGrupos
    Public Property clave As Long
    Public Property descripcion As String
    Public Property factorCosto As Decimal
    Public Property factorPublico As Decimal
    Public Property factorP1 As Decimal
    Public Property factorP2 As Decimal
    Public Property factorP3 As Decimal

End Class
