'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblHistorialPagos
    Public Property IdComp As String
    Public Property Id As Long
    Public Property fecha As Date
    Public Property numeroVenta As String
    Public Property total As Nullable(Of Decimal)
    Public Property claveCliente As String
    Public Property cliente As String
    Public Property observaciones As String
    Public Property tipoDocumento As String

End Class
