'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblHistorialPagos
    Public Property Id As Long
    Public Property fecha As Date
    Public Property numeroVenta As String
    Public Property total As Nullable(Of Decimal)
    Public Property claveCliente As String
    Public Property cliente As String
    Public Property observaciones As String
    Public Property tipoDocumento As String

End Class
