'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblHistorialPagosProveedores
    Public Property IdComp As String
    Public Property id As Long
    Public Property fecha As Date
    Public Property numeroCompra As String
    Public Property total As Decimal
    Public Property claveProveedor As Long
    Public Property proveedor As String
    Public Property observaciones As String
    Public Property movimientoPagar As Long

End Class
