'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblNC
    Public Property n_nc As Decimal
    Public Property SubTotal As Nullable(Of Decimal)
    Public Property IVA As Nullable(Of Decimal)
    Public Property total As Decimal
    Public Property usuario As String
    Public Property tipo_venta As String
    Public Property cliente As String
    Public Property id_cliente As String
    Public Property fecha_venta As Date
    Public Property fecha_limite As Nullable(Of Date)
    Public Property codiciones As String
    Public Property estado As String
    Public Property observaciones As String
    Public Property FolioFactura As String
    Public Property metodopago As String
    Public Property FormaPago As String
    Public Property UsoCFDI As String

End Class
