'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblOrdenCompraDe
    Public Property IdComp As String
    Public Property folio As String
    Public Property cantidad As String
    Public Property codigo As String
    Public Property concepto As String

End Class
