'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblProductos
    Public Property IdComp As String
    Public Property IdProducto As Long
    Public Property codigoBarras As String
    Public Property clave As String
    Public Property descripcionProducto As String
    Public Property unidadMedida As String
    Public Property marca As String
    Public Property grupo As String
    Public Property familia As String
    Public Property subfamilia As String
    Public Property linea As String
    Public Property proveedor As String
    Public Property tipoVenta As String
    Public Property descuento As Nullable(Of Decimal)
    Public Property precioLista As Decimal
    Public Property precioCosto As Nullable(Of Decimal)
    Public Property precioPublico As Nullable(Of Decimal)
    Public Property precioP1 As Nullable(Of Decimal)
    Public Property precioP2 As Nullable(Of Decimal)
    Public Property precioP3 As Nullable(Of Decimal)
    Public Property stock As Decimal
    Public Property precioManual As Integer
    Public Property Inventario As Boolean
    Public Property UsarTC As Nullable(Of Boolean)
    Public Property TC As Nullable(Of Decimal)
    Public Property ClaveProducto As String
    Public Property ClaveUnidad As String
    Public Property TasaCero As Nullable(Of Boolean)

End Class
