'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblTicket
    Public Property Id As Integer
    Public Property folio As String
    Public Property IdProducto As Long
    Public Property concepto As String
    Public Property cantidad As Nullable(Of Decimal)
    Public Property precio As Nullable(Of Decimal)
    Public Property fecha As Nullable(Of Date)
    Public Property subtotal As Nullable(Of Decimal)
    Public Property clave_producto As String
    Public Property precioCosto As Decimal
    Public Property subtotalCosto As Decimal
    Public Property numeroFactura As String
    Public Property ClaveProducto As String
    Public Property ClaveUnidad As String
    Public Property TasaCero As Nullable(Of Boolean)

End Class
