'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblUsuarios
    Public Property id_user As Integer
    Public Property usuario1 As String
    Public Property contrasena As String
    Public Property privilegios As String
    Public Property nombreEmpleado As String

End Class
