'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblW_Usuarios
    Public Property IdComp As String
    Public Property id_user As Integer
    Public Property usuario1 As String
    Public Property contrasena As String
    Public Property privilegios As String
    Public Property nombreEmpleado As String

End Class
