'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblWVentasPedidos
    Public Property IdComp As String
    Public Property nticket As Long
    Public Property fecha As Nullable(Of Date)
    Public Property SubTotal As Nullable(Of Decimal)
    Public Property IVA As Nullable(Of Decimal)
    Public Property total As Nullable(Of Decimal)
    Public Property tipo As String
    Public Property usuario As String
    Public Property cliente As String
    Public Property idCliente As Long
    Public Property estado As String
    Public Property motivo As String
    Public Property numeroFactura As String

End Class
