'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblWConfiguracion
    Public Property IdComp As String
    Public Property Id As Long
    Public Property IdTerminal As String
    Public Property nombreEmpresa As String
    Public Property direccionEmpresa As String
    Public Property localidadEmpresa As String
    Public Property telefonoEmpresa As String
    Public Property ciudadEmpresa As String
    Public Property rfcEmpresa As String
    Public Property propietario As String
    Public Property impresiones As Nullable(Of Integer)
    Public Property factorIVA As Decimal
    Public Property cajaChica As Decimal
    Public Property logotipo As String
    Public Property folioFactura As Long
    Public Property InvoicePrinterName As String
    Public Property TicketPrinterName As String
    Public Property TipoCambio As Nullable(Of Decimal)
    Public Property RegimenFiscal As String
    Public Property LugarExpedicion As String

End Class
