'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ticket_com
    Public Property IdComp As String
    Public Property folio As String
    Public Property concepto As String
    Public Property cantidad As Nullable(Of Decimal)
    Public Property precio As Nullable(Of Decimal)
    Public Property fecha As Nullable(Of Date)
    Public Property subtotal As Nullable(Of Decimal)
    Public Property clave_producto As String
    Public Property proveedor As String
    Public Property ClaveProducto As String
    Public Property ClaveUnidad As String
    Public Property TasaCero As Byte()

End Class
